CREATE TABLE IF NOT EXISTS `wf_task` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '唯一标识，主键ID',
  `uid` bigint(20) NOT NULL COMMENT 'uid',
  `graph_id` varchar(255) NOT NULL COMMENT '图ID',
  `instance_id` varchar(255) DEFAULT NULL COMMENT '流程实例id',
  `node_id` text NOT NULL COMMENT '图节点id',
  `node_type` varchar(255) DEFAULT NULL COMMENT '节点类型',
  `status` int(11) NOT NULL COMMENT '状态 0 待办 1 已办 2 终止 3 挂起',
  `status_msg` varchar(255) NOT NULL COMMENT '状态描述',
  `node_param` varchar(512) NOT NULL COMMENT '节点参数',
  `before_param` text COMMENT '任务执行前的参数',
  `after_param` text COMMENT '任务执行后的参数结果',
  `task_response` text NOT NULL COMMENT '任务执行返回结果',
  `callback_response` text NOT NULL COMMENT '回调结果',
  `run_count` int(11) DEFAULT '0' COMMENT '任务执行次数',
  `start_time` datetime DEFAULT NULL COMMENT '开始时间',
  `end_time` datetime DEFAULT NULL COMMENT '结束时间',
  `create_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `is_delete` tinyint(4) NOT NULL DEFAULT '0' COMMENT '删除标识 0-未删除 1-已删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_uid_graph_instance_node` (`uid`,`graph_id`,`instance_id`,`node_id`(255)),
  KEY `idx_instance_status` (`instance_id`, `status`),
  KEY `idx_uid_status` (`uid`, `status`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT='工作流任务表';
